### ISSUE TITLE
Question about the coordinate in the instruction

### ISSUE THREAD

**Issue by Richar-Du** [FuxiaoLiu/LRV-Instruction#14]
Thanks for your awesome work! I notice that there are some data containing coordinate of the bounding box, for example:

```
question: Are the white feathers of a bird at X:437 Y:0 with Width:60 Height:60?
answer: These dimensions and coordinates refer to the green foliage in the background, not white feathers of a bird.
task: negative
```
However, all the images have been resized before training. For example, Minigpt-4 has resized the images to 224*224, which is smaller than the range of the coordinate. I wonder how to deal with such cases. Thanks in advance :)

**Comment by FuxiaoLiu** [comment]
Thanks for your comments! In order to ensure the quality of the dataset right now. We remove the instructions with the coordinates for now. You can download the updated version  from [here](download.txt#L30). 

As for the future plan, we will also plan resize the the coordinates in the instructions based on the new image size 224*224 and the original image size. We will release them in the next week.

**Comment by Richar-Du** [comment]
Great! Thanks for your effort and we're looking forward to your update :)
