### ISSUE TITLE
About instruction data

### ISSUE THREAD

**Issue by JKBox** [FuxiaoLiu/LRV-Instruction#17]
Thanks for your nice work! 
However, I'm confused about the download data in https://github.com/FuxiaoLiu/LRV-Instruction/blob/main/download.txt
What the difference between these four data, in L5, L21, L28 and L31?

**Comment by BlueBlueFF** [comment]
same questions

**Comment by FuxiaoLiu** [comment]
Sorry for my late response! I am working on the CVPR deadline this week. As for L5, it's the first version of our dataset containing 150k data. L21 is the second version of our data contains additional 180k data. As for L28 and L31, we remove the instructions and answers with the coordinates since we found sometimes the coordinates generated by GPT4 is not very accurate. If you have more questions, feel free to let me know. Thanks!
